channels:
  - conda-forge
dependencies:
  - dask
  - earthaccess
  - fsspec
  - geopandas
  - h5netcdf
  - ipykernel
  - ipywidgets
  - kerchunk
  - libnetcdf
  - hdf5>=2.0
  - msgspec
  - rioxarray
  - xarray>=2026.04
platforms:
  - linux-64
  - osx-arm64
